### PR TITLE
Add bearing and url

### PR DESCRIPTION
**Pull request by yanokwa**

### CODE REVIEW

**Comment by MartijnR** [comment]
Interesting... Are these new or old undocumented widgets?

**Comment by yanokwa** [comment]
Undocumented in XLSForm. They've been in Collect for a while and listed at https://opendatakit.org/help/form-design/examples.

**Comment by MartijnR** [comment]
Ah, thanks. Now I get it. Appearance=bearing is for type=decimal. The PR has type=text. Phew, I was about to become disappointed ;)

All else look good to me.

**Comment by yanokwa** [comment]
Thanks for the review! The changes you requested have been made.

**Comment by MartijnR** [comment]
:) excellent work!

**Pull request merged**
