### PR TITLE
Markdown/HTML support

### PR DESCRIPTION
**Pull request by yanokwa**
@MartijnR You should probably view this

### CODE REVIEW

**Comment by MartijnR** [comment]
Thanks for doing this Yaw!

I'd just want to take out `For more advanced users, ODK Collect also supports HTML tags like <br>, <big>, <small>, and <h1> through <h6>`. Since we had agreed not to do this... ;) (Some are invalid HTML and all can be done with `<span>` or \# instead.) Maybe keep this _silently_ supported in ODK Collect?

In that case we can also take out the historic enketo-specific _visually merging of notes_ section, imho, as well as the link to Enketo's /better-notes/ blog post. 

I think both these changes would be very good for XLSForm users.

If those "unofficial" HTML tags remain in Nafundi's blog post and sample XLSForm, I propose to link to http://blog.enketo.org/more-markdown/ instead, since it only documents what we agreed to support. I can add emoji's though. I had no idea we could use those! 👍  Very cool!  :dromedary_camel:

**Comment by yanokwa** [comment]
I'd like to leave the HTML sentence. We said we'd add Markdown not remove HTML (even if there are 💩  tags that Android supports). There are enough undocumented differences (e.g., required questions in Enketo) across the tools as is and I don't want to make that worse. 🙏 

Perhaps we can add language about HTML tags not being recommended if you use Enketo in the XLSForm docs and Nafundi blog post?

I think we should leave the link to the Nafundi post because it shows you what things look like in Collect and that's important to users. And agreed that we should link to the more markdown post when we refer to the Enketo in that same section for the same reason.

Agreed that we can strike the styling visual notes section.

**Comment by MartijnR** [comment]
I'm a bit surprised that you insist on documenting a _duplicate_ method that is only supported in one client. It's unhelpful to users in my opinion. I can see us answering support questions explaining that users should use `**strong**` instead of `<b>strong</b>` to get a form that works in all clients. Seems very unnecessary.

Enketo and its supporters have been trying hard to eliminate differences on shared features with ODK Collect and made great progress in the past year. This discussion illustrates that it is unfortunately still a bit of a one-sided effort. Another example is the surprise addition of 11 new XPath methods in ODK Collect last week - though I am fully in favour of those methods and quickly added them to Enketo. I understand it's faster to just go it alone and clients may not care, but we're not talking about for a huge collaboration burden here. It's about wanting to be part of an ecosystem or trying to dominate one.

P.S. I mentioned it to you before but that required-question-difference is no longer there. It was eliminated [half a year ago](http://blog.enketo.org/page-validation/). Your feedback was valuable in doing that.

**Comment by yanokwa** [comment]
I've done what I can do and given my constraints. Feel free to adjust the PR as you see fit.

**Comment by MartijnR** [comment]
Thanks. Will do.

**Comment by MartijnR** [comment]
added new PR here: https://github.com/XLSForm/xlsform.github.io/pull/68

**Pull request closed without merging**
