### PR TITLE
chore: add startswith, endswith, contains and matches to search() docs

### LINKED ISSUE #166: Add startswith, endswith, contains and matches to existing search docs
Initial discussion: https://forum.opendatakit.org/t/looking-for-an-old-documentation-page-about-search-function/20594/3

Content: http://web.archive.org/web/20170710045637/https://opendatakit.org/help/form-design/data-preloading/

### PR DESCRIPTION
**Pull request by jniles**
Adds in missing documentation to the `search()` docs.

Closes #166

### CODE REVIEW

**Review by ukanga — APPROVED** [review]

**Comment by lognaturel** [comment]
@msschroeder @ukanga Have either of you verified these recently? They're Collect-only and have no automated test coverage. The Collect team has not intentionally removed or broken the functionality but don't maintain it. If you prefer to have it in for now, that's ok, but I do think we should make it very clear that `select_one_from_file` with a choice filter is the recommended way to build a filtered choice list from a CSV. Last we checked with analytics, `search()` was not in frequent usage.

**Comment by msschroeder** [comment]
@lognaturel I have used one not too long ago. But, I can confirm it next week. However, we can add content specifying the recommended approach using `select_one_from_file` with a choice filter is the recommended way to build a filtered choice list from a CSV

**Comment by lognaturel** [comment]
> can you filter an external CSV by multiple fields?

Yes, you can write a choice filter the same way you would for an internal select. In the `choice_filter` column for a `select_one_from_file`, you could use `province = ${province} and health_zone = ${health_zone}`. This will work in Enketo or Collect.

Currently I would expect a noticeable performance difference between the two approaches with about 60k+ items on a modern device. This is likely to go away within the next couple of Collect releases at which time we'll more explicitly phase out `search()`.

**Comment by msschroeder** [comment]
@lognaturel If it is going to be depreciated, it might be better not to reference this as much as it is with this pull request. Can I propose instead that we link the documentation to [this link](http://web.archive.org/web/20170710045637/https://opendatakit.org/help/form-design/data-preloading/) and mention more clearly the select_one_from file using a choice filter? What are your thoughts?

**Pull request merged**
